### PR TITLE
Add !help command

### PR DESCRIPTION
**Pull request by PurpleMyst**
This is still a draft as I've not been able to test it (I'm trying to wait for WSL2 since they may update is out, just not for my machine, 😞) but I thought that making a branch & draft PR would be good for communication.

The approach here is *very* simplistic: For each `Module`, output its name as a bolded line and then output a codeblock with its command handler's `Command::help` (or "No command." if there is none).

Let me know what you think of this approach and I'll refine it as needed.

Closes: #4

### CODE REVIEW

**Comment by PurpleMyst** [comment]
I'll switch to DMs, but I'm not sure what the advantage of embeds over codeblocks is?

**Comment by PurpleMyst** [comment]
I've made the suggested changes however I'm not able to test them still. Once you have the time, could you walk me through setting glimbot up as a Docker container? (such that for the time being I can test her on an rpi and move onto wsl2 once that's released)

**Comment by nes77** [comment]
> I'll switch to DMs, but I'm not sure what the advantage of embeds over codeblocks is?

[Embeds allow far more text in a single message](https://discord.com/developers/docs/resources/channel#embed-limits) than regular messages; the limit in a message is 2000 bytes; the limit in an embed is in the kilobytes.

**Comment by nes77** [comment]
We should eventually add a message in the server to say that we responded to the command.

**Pull request merged**
